#!/usr/bin/env bash
# setup-skills.sh — UniSkill Tool Suite Integration Script
# Usage: curl -fsSL https://uniskill-web.vercel.app/setup-skills.sh | bash -s -- <YOUR_TOKEN>
#
# What this script does:
#   1. Validates the provided API token
#   2. Writes UNISKILL_API_KEY into your project .env
#   3. Generates an OpenClaw-compatible tool manifest (uniskill-tools.yaml)
#   4. Prints a Trust Badge confirmation
#
# 使用方式：将 API token 作为第一个参数传入，脚本自动完成环境配置和清单生成

set -e

# ── 参数接收 ─────────────────────────────────────────────────────────────
TOKEN="${1:-}"

# 校验 token 是否传入，缺失则提前退出
if [[ -z "$TOKEN" ]]; then
    echo ""
    echo "❌  Error: API token is required."
    echo "    Usage: curl -fsSL https://uniskill-web.vercel.app/setup-skills.sh | bash -s -- <YOUR_TOKEN>"
    echo ""
    exit 1
fi

# ── 打印标题横幅 ─────────────────────────────────────────────────────────
echo ""
echo "🛠   UniSkill Tool Suite Integration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Step 1: 写入 UNISKILL_API_KEY 到 .env ────────────────────────────────
# 检测当前目录是否已有 .env 文件
ENV_FILE=".env"
ENV_KEY="UNISKILL_API_KEY"

if [[ -f "$ENV_FILE" ]]; then
    # .env 已存在：判断 key 是否已写入，有则替换，无则追加
    if grep -q "^${ENV_KEY}=" "$ENV_FILE"; then
        # macOS 与 Linux 的 sed -i 参数有差异，需兼容处理
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^${ENV_KEY}=.*|${ENV_KEY}=${TOKEN}|" "$ENV_FILE"
        else
            sed -i "s|^${ENV_KEY}=.*|${ENV_KEY}=${TOKEN}|" "$ENV_FILE"
        fi
        echo "✅  Updated ${ENV_KEY} in existing ${ENV_FILE}"
    else
        # 追加到已有 .env，前置空行保证格式整洁
        echo "" >> "$ENV_FILE"
        echo "# UniSkill API Key — added by setup-skills.sh" >> "$ENV_FILE"
        echo "${ENV_KEY}=${TOKEN}" >> "$ENV_FILE"
        echo "✅  Appended ${ENV_KEY} to existing ${ENV_FILE}"
    fi
else
    # .env 不存在：创建新文件并写入 key
    cat > "$ENV_FILE" <<EOF
# UniSkill API Key — generated by setup-skills.sh
${ENV_KEY}=${TOKEN}
EOF
    echo "✅  Created ${ENV_FILE} with ${ENV_KEY}"
fi

# ── Step 2: 生成 OpenClaw 工具清单文件 ───────────────────────────────────
# 清单遵循 OpenClaw Tool Manifest 规范，描述每个 UniSkill 技能端点的名称、描述和参数
MANIFEST_FILE="uniskill-tools.yaml"

cat > "$MANIFEST_FILE" <<YAML
# uniskill-tools.yaml — Generated by UniSkill setup-skills.sh
# OpenClaw Tool Manifest — describes UniSkill skill endpoints as callable tools
# 此文件由 setup-skills.sh 自动生成，描述 UniSkill 各项技能的工具定义

version: "1.0"
provider: UniSkill
base_url: https://gateway.uniskill.io

tools:
  # 全网搜索技能：基于 Tavily Search API
  - name: uniskill_search
    description: Search the web for real-time information using the UniSkill Search skill.
    endpoint: /v1/search
    method: POST
    parameters:
      - name: query
        type: string
        required: true
        description: The search query string.
      - name: max_results
        type: integer
        required: false
        description: Maximum number of results to return (default 5).

  # 网页抓取技能：基于 Jina AI Reader
  - name: uniskill_scrape
    description: Scrape and extract clean text content from any URL.
    endpoint: /v1/scrape
    method: POST
    parameters:
      - name: url
        type: string
        required: true
        description: The URL of the page to scrape.

  # 新闻搜索技能：基于 Tavily News 模式
  - name: uniskill_news
    description: Search for recent news articles on a given topic.
    endpoint: /v1/news
    method: POST
    parameters:
      - name: query
        type: string
        required: true
        description: The news search query.
      - name: days
        type: integer
        required: false
        description: Look back this many days (default 3).

  # 社交数据技能（即将上线）
  - name: uniskill_social
    description: Search social platforms for mentions and discussions (coming soon).
    endpoint: /v1/social
    method: POST
    parameters:
      - name: query
        type: string
        required: true
        description: The social search query.
YAML

echo "✅  Generated OpenClaw tool manifest: ${MANIFEST_FILE}"

# ── Step 3: 打印 Trust Badge 及完成摘要 ──────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉  Setup complete!"
echo ""
echo "   ✅  UNISKILL_API_KEY   →  .env"
echo "   ✅  Tool manifest      →  uniskill-tools.yaml"
echo ""
# Trust Badge：向用户保证现有 LLM 配置不受影响
echo "   🛡   Your local LLM settings remain untouched."
echo "       UniSkill operates as an independent tool provider"
echo "       alongside your existing OpenAI / Claude configuration."
echo ""
echo "   📖  Docs:  https://uniskill.io/docs"
echo "   🔧  Tools: $(wc -l < "$MANIFEST_FILE" 2>/dev/null | tr -d ' ') lines written to uniskill-tools.yaml"
echo ""
